### ISSUE TITLE
Missing `init` method

### ISSUE THREAD

**Issue by brandonramirez** [hapijs/good-file#57]
I am simply trying to create a `good-file` reporter with this configuration.  After fixing issue #56 I get this error:

    01:49:08.694Z FATAL server: worker 3(pid 4123) died. restarting...
    /Users/brandon/Desktop/boards-api/node_modules/good/node_modules/hoek/lib/index.js:683
        throw new Error(msgs.join(' ') || 'Unknown error');
              ^
    Error: Every reporter object must have an init method
        at Object.exports.assert (/Users/brandon/Desktop/boards-api/node_modules/good/node_modules/hoek/lib/index.js:683:11)
        at /Users/brandon/Desktop/boards-api/node_modules/good/lib/monitor.js:147:14
        at iterate (/Users/brandon/Desktop/boards-api/node_modules/good/node_modules/items/lib/index.js:35:13)
        at Object.exports.serial (/Users/brandon/Desktop/boards-api/node_modules/good/node_modules/items/lib/index.js:38:9)
        at internals.Monitor.start (/Users/brandon/Desktop/boards-api/node_modules/good/lib/monitor.js:123:11)
        at Object.exports.register (/Users/brandon/Desktop/boards-api/node_modules/good/lib/index.js:17:20)
        at /Users/brandon/Desktop/boards-api/node_modules/hapi/lib/plugin.js:242:14
        at iterate (/Users/brandon/Desktop/boards-api/node_modules/hapi/node_modules/items/lib/index.js:35:13)
        at Object.exports.serial (/Users/brandon/Desktop/boards-api/node_modules/hapi/node_modules/items/lib/index.js:38:9)
        at internals.Plugin.register (/Users/brandon/Desktop/boards-api/node_modules/hapi/lib/plugin.js:224:11)

This is my configuration:

    {
        reporters: [{
          reporter: require('good-file'),
          events: { ops: '*' },
          config: { path: nconf.get('log:root'), prefix: 'ops', rotate: 'daily' }
        }, {
          reporter: require('good-file'),
          events: { request: '*' },
          config: { path: nconf.get('log:root'), prefix: 'request', rotate: 'daily' }
        }]
      }

**Comment by arb** [comment]
You are using a new version of good with an old version of good-file. Try upgrading the major version of good-file. I am surprised you aren't getting any warnings when you do `npm install` because there are peerDependencies set up for this package.

**Comment by brandonramirez** [comment]
Ok.  I did a `npm install --save good@latest` followed by `npm install --save good-file@latest`.  Perhaps the `latest` tags are not in sync, causing incompatible versions.  In any event, I will try to grab the latest version of `good-file` now that I know it's a version conflict.

Thanks!

**Comment by brandonramirez** [comment]
Works great, thanks!

**Comment by midnightcodr** [comment]
Hi there I am running into a similar issue even my `good` and `good-console` have the same major version numbers:

> good: 6.4.0
> good-console: 6.3.1
> 
> node: 4.6.2
> npm: 2.15.11
> 

Error: reporter [0] must have an init method

**Comment by arb** [comment]
Change good-console to 5.3.2

**Comment by midnightcodr** [comment]
Thanks @arb that fixed it.
